services:
#  app:
#    build:
#      context: .
#    container_name: mishanya-moneta
#    depends_on:
#      - redis
#    ports:
#      - 8080:8080

  redis:
    image: 'redis:latest'
    environment:
      - REDIS_PORT=6379
    ports:
      - 6379:6379
#  volumes:
#    - ~/data/redis:/var/lib/redis
#    - ~/data/redis/config:/usr/local/etc/redis/redis.conf